version: '2.1'

executors:
  builder:
    docker:
    - image: circleci/golang:1.15
    working_directory: /go/src/app

workflows:
  version: 2
  test_and_build:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - build:
        requires: [test]
        filters:
          tags:
            only: /.*/
    - release:
        requires: [build]
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^\d+\.\d+\.\d+$/

jobs:
  test:
    executor: builder
    steps:
    - checkout
    - restore_cache:
        keys:
        - mod-{{ checksum "go.sum" }}
        - mod-
    - run: make test
    - save_cache:
        key: mod-{{ checksum "go.sum" }}
        paths:
        - "/go/pkg"

  build:
    executor: builder
    environment:
      BUILD_GOOS: darwin
      BUILD_GOARCH: amd64
      CGO_ENABLED: 1
    steps:
    - checkout
    - run: go get -u github.com/mitchellh/gox
    - restore_cache:
        keys:
        - mod-{{ checksum "go.sum" }}
        - mod-
    - run: make package
    - save_cache:
        key: mod-{{ checksum "go.sum" }}
        paths:
        - "/go/pkg"
    - persist_to_workspace:
        root: .
        paths:
        - Makefile
        - pkg/tmuxist_*
    - store_artifacts:
        path: pkg

  release:
    executor: builder
    steps:
    - run: go get -u github.com/tcnksm/ghr
    - attach_workspace:
        at: .
    - run: make release
